---
- hosts: local
  gather_facts: yes
  remote_user: root
  vars:
    newps: "newps:"

  tasks:
    - name: "Get Date"
      shell: date +%Y%m%d
      register: localdate
    - name: "Create password"
      shell:
         openssl rand -base64 8
      register: ps
    - name: "Create Password File"
      debug:
        msg: "NewPassword is: {{ ps.stdout }}"
    - name: "Create Password File"
      shell:
        echo "{{ newps }}" "{{ ps.stdout }}" > /var/lib/awx/projects/test/ps.yml
    - name: "Create Password Date Dir"
      file:
        path: /var/lib/awx/projects/test/{{ localdate.stdout }}
        state: directory
        mode: 0777
    - name: "Copy Password File to Date Dir"
      copy:
        src: /var/lib/awx/projects/test/ps.yml
        dest: /var/lib/awx/projects/test/{{ localdate.stdout }}/
